### ISSUE TITLE
Error in Streambuilder when copying Example Project

### ISSUE THREAD

**Issue by samuelmukoti** [yringler/just_audio_service#2]
Hi,  

Been trying to use your library by copying the implimentation from the included example.  Not sure what I'm doing wrong but I get an error when creating a streambuilder instance as you can see in the image attached below.  Please may you point me in the right direction?

<img width="1357" alt="Screen Shot 2020-06-13 at 11 13 18 AM" src="https://user-images.githubusercontent.com/6235215/84576159-6f5faf80-ad67-11ea-873c-dcb70b84dcd1.png">

**Comment by samuelmukoti** [comment]
I'm sorry, I found the mistake that I'd made.

**Comment by yringler** [comment]
Not a problem!
First of all, I'm thrilled that you're using this and (hopefully) finding it helpful.
Keep in mind, though, that it's still a work in progress. Basic issues have been resolved as I have started using it in my own app, but there are some more to deal with. (I noticed that something wasn't working right if I killed the app while the background task was running. It doesn't effect me because I start audio_service with the option to kill the service if the app is killed, but that bug might still be there.)
PRs / forks are always welcome.
