### ISSUE TITLE
Sync different isolate state

### ISSUE THREAD

**Issue by mohammadne** [yringler/just_audio_service#9]
hi @yringler 

I want to use ```audio service``` plugin but I have some problems.
as you mentioned how we can keep track of position to save it on hive ?
or in my use case I have multiple ```playing state``` like :
shuffle , PlayInOrder , ... .

but I am confused how to implement this features because they are on different isolates and 
necessary to be sync in isolates.

now I want to know what is your solution ?
I aimed to use hive db , but it has some problems on different isolates.

**Comment by yringler** [comment]
It's hard to say exactly because I don't have the clearest view of your code.
But in general, you'll see in [position-data-manager.dart](https://github.com/yringler/just_audio_service/blob/master/lib/position-manager/position-data-manager.dart) that I have 3 classes:
1. one which uses hive,
1. one which communicates with another isolate, which _that_ isolate uses hive, and
1. a 3rd which helps figure out which one should be used.

Possibly you can repurpose that for your needs, or, better yet, abstract a base class/ interface and have some sort of shared code going on.
